FROM ghcr.io/weaveworks/capmvm-kubernetes:1.21.8

RUN apt update &&  apt install -y nfs-common

ADD startup-home.sh /etc/init.d/startup.sh
RUN chmod +x /etc/init.d/startup.sh
ADD startup.service /etc/systemd/system/startup.service
RUN systemctl enable startup.service