name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image - home 
      run: docker build . --file Dockerfile.home --tag ${{ secrets.DOCKER_USERNAME }}/capmvm-kubernetes-home:${{ github.run_number }}
    - name: Build the Docker image - vod 
      run: docker build . --file Dockerfile.vod --tag ${{ secrets.DOCKER_USERNAME }}/capmvm-kubernetes-vod:${{ github.run_number }}
    - name: push the Docker image - home
      run: docker push ${{ secrets.DOCKER_USERNAME }}/capmvm-kubernetes-home:${{ github.run_number }}
    - name: push the Docker image - vod
      run: docker push ${{ secrets.DOCKER_USERNAME }}/capmvm-kubernetes-vod:${{ github.run_number }}